# This is compose file using only local develop
version: "3.5"

services:
  db:
    image: timescale/timescaledb:latest-pg12-oss
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD:-postgres}
    ports:
      - ${APP_DB_PORT:-5432}:5432

  amqp:
    image: rabbitmq:3.8.2-management
    ports:
      - ${APP_AMQP_PORT:-5672}:5672
      - ${APP_AMQP_GUI_PORT:-15672}:15672

  balancer:
    image: nginx:1.17.8
    network_mode: host
    volumes:
      - ./nginx/develop.template:/etc/nginx/conf.d/default.template:ro
    command: /bin/bash -c "envsubst '$${API_LOC},$${GUI_LOC},$${WS_LOC}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    environment:
      - API_LOC=${APP_API_LOC:-http://127.0.0.1:8000}
      - GUI_LOC=${APP_GUI_LOC:-http://127.0.0.1:3000}
      - WS_LOC=${APP_GUI_LOC:-http://127.0.0.1:8080}

volumes:
  db: {}
